name: CI Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Vowel Frequency Analyzer
        uses: ./.github/actions/vowel-frequency-analyzer
        with:
          file: data.txt
        env:
          GITHUB_USER: ${{ github.actor }}
